openapi: '3.0.1'
info:
  title: 'EA_NWS_API'
  version: '1.0.0'
paths:
  /member/signinStart:
    $ref: './paths/signin/signInStart.yaml'
  /member/signinValidate:
    $ref: './paths/signin/signInValidate.yaml'
  /member/registerStart:
    $ref: './paths/signup/registerStart.yaml'
  /member/registerOrgStart:
    $ref: './paths/signup/registerOrgStart.yaml'
  /member/registerValidate:
    $ref: './paths/signup/registerValidate.yaml'
  /member/updateProfile:
    $ref: './paths/update-profile/updateProfile.yaml'
  /member/verifyMobilePhoneStart:
    $ref: './paths/contact/mobile/verifyMobilePhoneStart.yaml'
  /member/verifyMobilePhoneValidate:
    $ref: './paths/contact/mobile/verifyMobilePhoneValidate.yaml'
  /member/verifyHomePhoneStart:
    $ref: './paths/contact/homePhone/verifyHomePhoneStart.yaml'
  /member/verifyHomePhoneValidate:
    $ref: './paths/contact/homePhone/verifyHomePhoneValidate.yaml'
  /member/verifyEmailStart:
    $ref: './paths/contact/email/verifyEmailStart.yaml'
  /member/verifyEmailValidate:
    $ref: './paths/contact/email/verifyEmailValidate.yaml'
  /member/registerToPartner:
    $ref: './paths/partner/registerToPartner.yaml'
  /member/deleteAccount:
    $ref: './paths/account/deleteAccount.yaml'
