openapi: '3.0.1'
info:
  title: 'EA_NWS_API'
  version: '1.0.0'
paths:
  /member/signinStart:
    $ref: './paths/signin/signInStart.yaml'
  /member/signinValidate:
    $ref: './paths/signin/signInValidate.yaml'
  /member/registerStart:
    $ref: './paths/signup/registerStart.yaml'
  /member/registerValidate:
    $ref: './paths/signup/registerValidate.yaml'
  /member/updateProfile:
    $ref: './paths/update_profile/updateProfile.yaml'
  /member/verifyMobilePhoneStart:
    $ref: './paths/signup/channel-preferences/mobile/verifyMobilePhoneStart.yaml'
  /member/verifyMobilePhoneValidate:
    $ref: './paths/signup/channel-preferences/mobile/verifyMobilePhoneValidate.yaml'
  /member/verifyHomePhoneStart:
    $ref: './paths/signup/channel-preferences/homePhone/verifyHomePhoneStart.yaml'
  /member/verifyHomePhoneValidate:
    $ref: './paths/signup/channel-preferences/homePhone/verifyHomePhoneValidate.yaml'
