# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG NODE_VERSION=17.9.1

################################################################################
# Use node image for base image for all stages.
FROM node:${NODE_VERSION}-alpine as base

# Set working directory for all build stages.
WORKDIR /usr/src/app

################################################################################
# Create a stage for building the application.
FROM base as api_build

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
# into this layer.
RUN --mount=type=bind,source=api/package.json,target=package.json \
    --mount=type=bind,source=api/package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

# Copy the rest of the source files into the image.
COPY api .

################################################################################
# Create a new stage to run the application with minimal runtime dependencies
# where the necessary files are copied from the build stage.
FROM base as final

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV


# Copy package.json so that package manager commands can be used.
COPY api/package.json .
COPY api/index.ts .

# Copy the production dependencies from the deps stage and also
# the built application from the build stage into the image.
COPY --from=api_build /usr/src/app/node_modules ./node_modules
COPY --from=api_build /usr/src/app/handlers ./handlers
COPY --from=api_build /usr/src/app/openapi ./openapi

# Expose the port that the application listens on (api).
EXPOSE 9000

RUN chown -R node /usr/src/app/node_modules

USER node
# Run the application.
CMD npx ts-node index.ts
