# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG NODE_VERSION=17.9.1

################################################################################
# Use node image for base image for all stages.
FROM node:${NODE_VERSION}-alpine as base

# Set working directory for all build stages.
WORKDIR /usr/src/app

################################################################################
# Create a stage for building the application.
FROM base as backend_build

# Copy the rest of the source files into the image.
COPY backend .

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
# into this layer.
RUN --mount=type=bind,source=backend/package.json,target=package.json \
    --mount=type=bind,source=backend/package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

# Run the build script.
RUN npm run build

################################################################################
# Create a new stage to run the application with minimal runtime dependencies
# where the necessary files are copied from the build stage.
FROM base as final

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

ARG API_URL
ENV API_URL $API_URL

# Copy package.json so that package manager commands can be used.
COPY backend/package.json .
COPY backend/index.js .

# Copy the production dependencies from the deps stage and also
# the built application from the build stage into the image.

# backend
COPY --from=backend_build /usr/src/app/node_modules ./node_modules
COPY --from=backend_build /usr/src/app/bin ./bin
COPY --from=backend_build /usr/src/app/client ./client
COPY --from=backend_build /usr/src/app/server ./server

# Expose the port that the application listens on (backend).
EXPOSE 5000

RUN chown -R node /usr/src/app/node_modules

USER node
# Run the application.
CMD node index.js