const AlertType = {
  SEVERE_FLOOD_WARNING: 'ALERT_LVL_1',
  FLOOD_WARNING: 'ALERT_LVL_2',
  FLOOD_ALERT: 'ALERT_LVL_3',
  REMOVE_FLOOD_SEVERE_WARNING: 'MONTHLY',
  REMOVE_FLOOD_WARNING: 'RESEVERVED',
  INFO: 'INFO'
}

export default AlertType
